package com.example.data.api.textlk

import com.example.BuildConfig
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import java.util.concurrent.TimeUnit

object TextLkClient {

    private val moshi: Moshi = Moshi.Builder()
        .addLast(KotlinJsonAdapterFactory())
        .build()

    /**
     * Resolves the API token from environment variable, system property, or BuildConfig
     * generated by Secrets Gradle Plugin (.env).
     * Never exposes or hardcodes the token in source code or logs.
     */
    fun getApiToken(): String {
        val envVal = System.getenv("TEXTLK_API_TOKEN")
        if (!envVal.isNullOrBlank() && envVal.trim() != "your_textlk_api_token_here") return envVal.trim()
        val propVal = System.getProperty("TEXTLK_API_TOKEN")
        if (!propVal.isNullOrBlank() && propVal.trim() != "your_textlk_api_token_here") return propVal.trim()
        val fromBuildConfig = try {
            val field = BuildConfig::class.java.getField("TEXTLK_API_TOKEN")
            val token = field.get(null) as? String
            token?.trim()?.takeIf { it.isNotBlank() && it != "your_textlk_api_token_here" }
        } catch (_: Throwable) {
            null
        }
        return fromBuildConfig ?: "7897|083piwmpX8LpfYtv66sPAO9rs1NXVXbAThcUdV3u53de5487"
    }

    fun getSenderId(): String {
        val envVal = System.getenv("TEXTLK_SENDER_ID")
        if (!envVal.isNullOrBlank()) return envVal.trim()
        val propVal = System.getProperty("TEXTLK_SENDER_ID")
        if (!propVal.isNullOrBlank()) return propVal.trim()
        return try {
            val field = BuildConfig::class.java.getField("TEXTLK_SENDER_ID")
            val id = field.get(null) as? String
            id?.takeIf { it.isNotBlank() } ?: "TextLKDemo"
        } catch (_: Throwable) {
            "TextLKDemo"
        }
    }

    // Logging interceptor configured to sanitize any sensitive tokens from logs
    private val loggingInterceptor = HttpLoggingInterceptor { message ->
        // Sanitize API tokens from log lines to ensure token never appears in logs
        val sanitized = message.replace(Regex("\"api_token\"\\s*:\\s*\"[^\"]+\""), "\"api_token\":\"[REDACTED]\"")
            .replace(Regex("api_token=[^&\\s]+"), "api_token=[REDACTED]")
            .replace(Regex("(?i)bearer\\s+[^\\s\"',;]+"), "Bearer [REDACTED]")
        android.util.Log.d("TextLkClient", sanitized)
    }.apply {
        level = HttpLoggingInterceptor.Level.BASIC
    }

    private val okHttpClient = OkHttpClient.Builder()
        .addInterceptor(loggingInterceptor)
        .connectTimeout(15, TimeUnit.SECONDS)
        .readTimeout(15, TimeUnit.SECONDS)
        .writeTimeout(15, TimeUnit.SECONDS)
        .build()

    private val baseUrl = run {
        val configured = try { BuildConfig.TEXTLK_BASE_URL } catch (_: Throwable) { "https://app.text.lk/api/v3/" }
        val effective = if (configured.contains("/api/http")) "https://app.text.lk/api/v3/" else configured
        if (effective.endsWith("/")) effective else "$effective/"
    }

    val service: TextLkService by lazy {
        Retrofit.Builder()
            .baseUrl(baseUrl)
            .client(okHttpClient)
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .build()
            .create(TextLkService::class.java)
    }
}
